services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - shell-out-network
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - shell-out-network

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - shell-out-network
    depends_on:
      - app
      - db
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          target: /var/www/html

networks:
  shell-out-network: